### ISSUE TITLE
Deadlock around ServiceBrowserNew

### ISSUE THREAD

**Issue by richardweinberger** [holoplot/go-avahi#10] opened 2020-12-29 11:43 UTC
On my Debian stretch system server.ServiceBrowserNew() does often not return, about 9 out of 10 times.
It blocks at ` err := c.object.Call(c.interfaceForMember("ServiceBrowserNew"), 0, iface, protocol, serviceType, domain, flags).Store(&o)` with `c.mutex.Lock()` held.

Do you have an idea what could cause this?

**Comment by zonque** [comment] 2021-01-22 09:31
Sorry for the long wait.

Could you monitor your bus with `busctl monitor` and see what calls are being made to the avahi daemon? If the DBus call hangs, the issue is likely not in `go-avahi` I figure. FWIW, I cannot see the issue here, and our code is based on `ServiceBrowserNew()` as well. Which version of avahi-daemon is this? Can you reproduce with the avahi tools?

**Comment by zonque** [comment] 2021-06-24 07:05
I'm closing this issue now as I got no reply. The code has changed a bit in that area, so chances are the issue has been addressed. Feel free to reopen if you still see the bug!

**Closed as completed by zonque** 2021-06-24 07:05 UTC
